### ISSUE TITLE
Lat Lon Reversed

### ISSUE THREAD

**Issue by rcreswell** [kneo/indi-bresserexos2#5] opened 2021-07-20 15:59 UTC
When using the INDI panel for the Bresser driver, setting the lat long entries appear to be reversed on the Exos-2GT handbox.  I noticed this when I was limited to setting the longitude to my meridian (-121). The INDI panel form limits the entry between (-90<x<90).  Further, when activating the 'Set' button, lat changes lon, and lon changes lat between the INDI panel and the handbox.

**Comment by kneo** [comment] 2021-07-20 21:25
Thanks, I suspected something like this, it is related if not cause of the Issue #4. I'm currently working on a 0.900 Version of the driver. I'll see to fix this issue in the near future.

**Comment by kneo** [comment] 2021-07-30 23:51
I added some changes to the latest dev_Ver0.900 commit (046e1aa565b0d6c4f7d210fc1d2d9486eb00b316). The boundaries for the longitude and latitude values were swapped. It should work correctly now. However I could not reproduce the cross swap of the geographic coordinates issue. 

Steps to reproduce:
I set both to something equal (eg. 10°), then change either of them to a significant different value (eg. 20). 
Outcome: I get the correct result. Latitude is indicated with N/S and longitude with E/W shown on the screen.

According to the firmware and driver I provide the data in the right order.

**Comment by rcreswell** [comment] 2021-07-31 00:31
Kevin,

 

Thanks for this incredibly fast response.  I will update the driver on Astroberry today and report back on the results.

 

Kind Regards,

 

Ron Creswell

Vacaville, CA

**Comment by rcreswell** [comment] 2021-08-03 04:32
Thank you very much for the update to the Explore Scientific FL-EXOS-2GT mount INDI driver.  All functions appear to be working well including the INDI Site Management - Scope Location and UTC settings.    Whatever was done has restored the scope location lat/lon function to the correct order and value range (e.g., I can enter coordinates 121W 38N without the INDI form rejecting the setting).

 

Also, I noticed another serendipity in that the PHD2 application now picks up the scope as a usable mount since it now has guiding capabilities.  In the previous version, it would not use the Bresser driver.

 

I wish to thank you again for the remarkable responsiveness that was shown in updating this driver.  For those of use wanting to use the FL-EXOS-2GT in the INDI environment,  your driver is the only one available for the mount.

 

I suspect that some of the reported mount behaviors reported by others will now disappear since the orientation parameters seem corrected.

 

Thanks again.  How can I contribute monetarily to your efforts?

 

Regards,

 

Ron Creswell

Vacaville, CA

 

ger ***@***.***> 
Sent: Friday, July 30, 2021 4:52 PM
To: kneo/indi-bresserexos2 ***@***.***>
Cc: rcreswell ***@***.***>; Author ***@***.***>
Subject: Re: [kneo/indi-bresserexos2] Lat Lon Reversed (#5)

 

I added some changes to the latest dev_Ver0.900 commit ( <https://github.com/kneo/indi-bresserexos2/commit/046e1aa565b0d6c4f7d210fc1d2d9486eb00b316> 046e1aa). The boundaries for the longitude and latitude values were swapped. It should work correctly now. However I could not reproduce the cross swap of the geographic coordinates issue.

Steps to reproduce:
I set both to something equal (eg. 10°), then change either of them to a significant different value (eg. 20).
Outcome: I get the correct result. Latitude is indicated with N/S and longitude with E/W shown on the screen.

According to the firmware and driver I provide the data in the right order.

**Comment by kneo** [comment] 2021-08-03 09:31
Hello @rcreswell,
thank you for your appreciation, but I do not seek monetary compensation for building this driver.

However I'm glad that your problem appears to be fixed now.

You may want to check out issue #3 for information and limitation regarding the current auto guiding implementation. 

clear skies!

**Closed by kneo** 2021-08-03 09:31 UTC
