### ISSUE TITLE
Add to INDI 3rd party?

### ISSUE THREAD

**Issue by knro** [kneo/indi-bresserexos2#1] opened 2021-03-09 21:34 UTC
Hello, great work on the driver! I just found about this today. Do you think this is ready for including in the official INDI 3rd party repository? This way it can receive more widespread testing.

**Comment by kneo** [comment] 2021-03-10 08:07
I'd like that, but I'd like to make sure it conforms to the indi guidelines, also there are some bugs with the sync function too.
I'm not sure when I find the time to do that, weather is anything but kind.

However, I'm honored to be considered for a 3rd Party inclusion.
If you don't mind my considerations, we can simply go ahead.

**Comment by knro** [comment] 2021-03-10 09:48
Sure, that would be great! Once it is there, it will be tested by the community and perhaps even fixes/improvements are submitted to address any issues! Please check if you can submit a PR and we'll work on that. Great job on the documentation as well!

**Comment by kneo** [comment] 2021-03-10 16:19
I never made a pull request. I'll look into it on the weekend.

**Comment by knro** [comment] 2021-03-18 15:56
Hello @kneo , any update on this? If you need help with creating the PR, please let me know so we can proceed.

**Comment by FocusAG** [comment] 2021-03-19 13:36
Hello @kneo. I'm one of the parts interested in make the driver for INDI to work, and I think that I was the one o put @knro in touch with you about a request that I made to his team a few days ago. I'm not a programer and I know almost nothing about programming. but I can help with the testings. I've just found out two problems on the driver.. actually tree of them. If your interested I can do some help on testing things. I have the mount, the goto system, guiding systems as well and Astroberry Pi as Stellarmate OS. 

I'll be waiting for news from you.

Thank your for this work of yours. I was almost giving up from this mount.

Regards,

Cesar

**Comment by kneo** [comment] 2021-03-20 10:21
Hello @knro @FocusAG,
despite my initial optimism I currently find myself in a position where I have to spoil anyones hopes with a good portion of pessimism, worst realism even.
I came to this conclusion after testing the last weeks, which is why I answer this late.

I can not publish this driver to a wide range user base with a clean conscience. 
It has to do with my standards of "good software" and the driver simply does not live up to that.
I really hate it when I find promissing open source software which breaks the moment the user hovers over the "wrong" buttons. This is the situation of the driver right now, in my opinion.
I don't want to spoil anyones precious observation time, with banale software errors.
This thing has to work reliably, no matter what.
The driver is what I call bad design and the only way to fix that is to remove motion commands and autoguiding completely. 
This will decrease complexity, and therefore increase stability.

This is not just an issue of craft but of foundation also.
Frankly the firmware basis of the Bresser EXOS II GoTo mount is a disgrace to any software developer and Bresser should be ashamed of still selling it.
Physically this thing is quite stable, it tracks clean, I did not notice any drift, when setup properly.
But the software side is awful, they simply abandoned it!

I'd rather focus my efforts for a clean handbox replacement, rather than being doomed to fix bugs which are caused by miscommunication - not-communication actually - between mount and driver for all eternity.
I already started reverse engineering on that.
But this will take some time to finish.
Also I'm confident that this is a better use of my precious spare time.

Now how I think how to resolve the current situation:

- I decided remove autoguiding and motion keys, you can still use ST4 and the HBX for this of course. 
- I will only implement basic setup, goto and sync commands, which I deem reliable.

Once at this stage I think its ok adding it to the 3rd party repository.
Making the user aware of its limitations of course.
I may add the stripped features at a later point, if I find a trustworthy way of implementing them.

Its not carved into stone, we can discuss about this. 
If you do not mind the state of the driver after reading my considerations, I'll add it asap.
However please keep in mind that I don't want to promise more than I'm able to deliver.

My time budget is limited as well, I still have a fulltime occupation.
So I can work on this on the weekend only.

I'm sorry to spoil anybodies hopes, but I don't trust this driver as far as I can throw its mount and I don't want anybody being fooled into using that.

**Comment by knro** [comment] 2021-03-20 11:38
@kneo Thank you for the feedback! It's greatly appreciated and I applaud your candor in this matter. It is important for the users to know about the limitation for this driver, especially since it is reversed engineering and the manufacturer is not interested to cooperate with 3rd party developers as far as I can tell.

We can add a disclaimer when using the driver about these limitations. For most users, a partially working driver is better than none at all. Furthermore, when the driver is INDI 3rd party and visible to more users (and developers), chances are someone would probably step in to fix any pending issues. Notwithstanding that, it's better to disable (comment out) any features you think are not usable at all up until the time when someone steps in to look at them.

Thank you for your work on this great project, I can see it took a lot of effort and time to get where you are today. Bravo!

**Comment by kneo** [comment] 2021-03-20 12:14
@knro I really underestimated what the effort I need to put into that.
I will simply PR the modified limited stable version in to a branch of the 3rd party repository and let you know when I'm done.
I hope to be finished within the next weeks but I don't want to commit to a fixed deadline. I currently lack the proper means to do this.

@FocusAG If you found issues, just open issues with a description and how to reproduce each of them.
This type of documentation will be helpful in the future. Thank you for your effort and motivation.

**Comment by FocusAG** [comment] 2021-04-05 01:52
Kevin, any help with this? Tried to install on the Stellarmate OS, did a few adjustments on you guidelines on how to install it but I'm stucked here.. on the CMake .. 

![20210405_014620](https://user-images.githubusercontent.com/80964892/113528782-2eb07b80-95b1-11eb-8b1c-91799b8d015f.jpg)

**Comment by kneo** [comment] 2021-04-05 09:56
Please continue in [this issue](https://github.com/kneo/indi-bresserexos2/issues/2#issue-850247113)

**Comment by knro** [comment] 2021-04-20 12:50
@kneo Do you require any assistance at this point to get this included in INDI 3rd party?

**Comment by kneo** [comment] 2021-04-20 12:58
I intend to integrate it into my fork on the week end. I just need to make sure that it builds as a whole. Once this succeeds I'll file the pull request.

**Comment by kneo** [comment] 2021-04-24 12:59
Hello @knro,
I finally managed to integrate the driver in a branch of the 3rd party driver repository. Also added the pull request already ... Since felt uncomfortable to merge it into the main branch I added my own for you to merge manually.

Please let me know if everything is alright so I can close this ticket.

**Comment by kneo** [comment] 2021-04-26 13:46
Pull Request merged into the 3rd Party Drivers repository. Issue Closed!

**Closed by kneo** 2021-04-26 13:46 UTC
